export const CATEGORIES = [
  'Textbooks',
  'Handwritten Notes',
  'Study Guides',
  'Notebooks',
  'Lab Manuals',
  'Calculators/Tools',
  'Coaching Materials',
  'Other'
];

export const DEPARTMENTS = [
  'CS', 'CS AI', 'CS CY', 'EEE', 'ECS', 'MCA', 'MBA', 'ME', 'Civil', 'AD'
];

export const LISTINGS = [
  {
    id: 1,
    title: 'Data Structures by Cormen - Like New',
    category: 'Textbooks',
    department: 'CS',
    semester: 'S3',
    subject: 'Data Structures',
    price: 450,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=Data+Structures',
    seller: 'Arjun K',
    isVerified: true,
    condition: 'Like New',
    featured: true,
  },
  {
    id: 2,
    title: 'Physics Handwritten Notes - S2',
    category: 'Handwritten Notes',
    department: 'CS',
    semester: 'S2',
    subject: 'Physics',
    price: 100,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=Physics+Notes',
    seller: 'Maya S',
    isVerified: true,
    condition: 'Good',
    featured: true,
  },
  {
    id: 3,
    title: 'GATE CSE Study Material',
    category: 'Study Guides',
    department: 'CS',
    semester: 'S8',
    subject: 'Competitive Exam',
    price: 600,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=GATE+Study',
    seller: 'Raj M',
    isVerified: true,
    condition: 'Like New',
    featured: true,
  },
  {
    id: 4,
    title: 'Practical Notebook ECS Lab',
    category: 'Notebooks',
    department: 'ECS',
    semester: 'S4',
    subject: 'Digital Electronics Lab',
    price: 150,
    isFree: false,
    status: 'Exchanged',
    image: 'https://via.placeholder.com/300x200?text=Lab+Notebook',
    seller: 'Akhil P',
    isVerified: true,
    condition: 'Good',
    featured: false,
  },
  {
    id: 5,
    title: 'Calculus Reference Guide',
    category: 'Study Guides',
    department: 'ME',
    semester: 'S2',
    subject: 'Calculus',
    price: 0,
    isFree: true,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=Calculus+Guide',
    seller: 'Sophia D',
    isVerified: true,
    condition: 'Like New',
    featured: true,
  },
  {
    id: 6,
    title: 'JEE Main Mathematics Notes',
    category: 'Coaching Materials',
    department: 'AD',
    semester: 'S6',
    subject: 'Mathematics',
    price: 300,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=JEE+Notes',
    seller: 'Vikram R',
    isVerified: false,
    condition: 'Used',
    featured: false,
  },
  {
    id: 7,
    title: 'Scientific Calculator - Casio',
    category: 'Calculators/Tools',
    department: 'EEE',
    semester: 'S1',
    subject: 'General',
    price: 1200,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=Calculator',
    seller: 'Neha G',
    isVerified: true,
    condition: 'Like New',
    featured: false,
  },
  {
    id: 8,
    title: 'Digital Logic Design Lab Manual',
    category: 'Lab Manuals',
    department: 'ECS',
    semester: 'S3',
    subject: 'Digital Logic Design',
    price: 80,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=Lab+Manual',
    seller: 'Karthik T',
    isVerified: true,
    condition: 'Good',
    featured: false,
  },
  {
    id: 9,
    title: 'C Programming by Balaguruswamy',
    category: 'Textbooks',
    department: 'CS AI',
    semester: 'S2',
    subject: 'Programming',
    price: 350,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=C+Programming',
    seller: 'Priya M',
    isVerified: true,
    condition: 'Good',
    featured: false,
  },
  {
    id: 10,
    title: 'Economics Study Notes',
    category: 'Study Guides',
    department: 'MBA',
    semester: 'S1',
    subject: 'Economics',
    price: 200,
    isFree: false,
    status: 'Active',
    image: 'https://via.placeholder.com/300x200?text=Economics',
    seller: 'Aditya K',
    isVerified: true,
    condition: 'Like New',
    featured: false,
  },
];
